### ISSUE TITLE
Inpainting producing poor results?

### ISSUE THREAD

**Issue by daniellochner** [lucidrains/imagen-pytorch#205] opened 2022-08-31 12:55 UTC
Hi there,

I'm trying to use the model I've trained to perform inpainting, but I'm not getting the best results:
![Inpainting_Error](https://user-images.githubusercontent.com/37551307/187681308-0c21fd90-7d80-42c3-8275-7aa355be63ed.png)

It has trained on over 150,000 images for 25 hours, and the results it generates on its own are fantastic! Here is a random example:
![sample-30-08-2022-22-33-59-0](https://user-images.githubusercontent.com/37551307/187682405-2297a531-9b94-4a40-ba9f-90180188fa60.png)

What am I doing wrong? [Here](https://github.com/daniellochner/terrain-ml) is a link to my repository, and [here](https://drive.google.com/file/d/1dMmtqHH6v90XAt1c_irsKS9JJSi8wP9h/view?usp=sharing) is a link to download my latest checkpoint as well if it helps.

Thank you for your time!

**Comment by lucidrains** [comment] 2022-08-31 14:57
@daniellochner Hi Daniel again! You are one of the first to test inpainting actually

I'm using the technique from [this paper](https://arxiv.org/abs/2201.09865)

I just reviewed the code and found a bug in the non-elucidated ddpm (elucidated seems fine, I think?)

Would you like to try version 1.11.4 and see if there is a difference?

**Comment by daniellochner** [comment] 2022-08-31 15:34
Ah fantastic, that definitely seems to have done the trick! Thank you so much!! :)
![image](https://user-images.githubusercontent.com/37551307/187718095-4e8c58ae-56de-4cdb-91fb-901e4b6f4cb7.png)

**Comment by lucidrains** [comment] 2022-08-31 15:36
@daniellochner no problem! thank you for confirming this works :)

**Comment by daniellochner** [comment] 2022-09-07 22:54
Hey again!

I can't seem to inpaint anymore? The Elucidated seems to work fine given the same input.

Here's the stack trace:
> Traceback (most recent call last):
>   File "d:\Education\University\2022\Project\Code\terrain-ml\src\terrain_eval.py", line 121, in <module>
>     run_u()
>   File "d:\Education\University\2022\Project\Code\terrain-ml\src\terrain_eval.py", line 114, in run_u
>     samples = imagen.sample(inpaint_images=inpaint_images, inpaint_masks=inpaint_masks, return_pil_images=True)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 99, in inner
>     out = fn(model, *args, **kwargs)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 2256, in sample
>     img = self.p_sample_loop(
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 2108, in p_sample_loop      
>     img, x_start = self.p_sample(
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 2033, in p_sample
>     (model_mean, _, model_log_variance), x_start = self.p_mean_variance(unet, x = x, t = t, t_next = t_next, noise_scheduler = noise_scheduler, text_embeds = text_embeds, text_mask = text_mask, cond_images = cond_images, cond_scale = cond_scale, lowres_cond_img = lowres_cond_img, self_cond = self_cond, 
> lowres_noise_times = lowres_noise_times, pred_objective = pred_objective, dynamic_threshold = dynamic_threshold)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 1986, in p_mean_variance    
>     pred = default(model_output, lambda: unet.forward_with_cond_scale(x, noise_scheduler.get_condition(t), text_embeds = text_embeds, text_mask = text_mask, cond_images = cond_images, cond_scale = cond_scale, lowres_cond_img = lowres_cond_img, self_cond = self_cond, lowres_noise_times = self.lowres_noise_schedule.get_condition(lowres_noise_times)))
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 66, in default
>     return d() if callable(d) else d
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 1986, in <lambda>
>     pred = default(model_output, lambda: unet.forward_with_cond_scale(x, noise_scheduler.get_condition(t), text_embeds = text_embeds, text_mask = text_mask, cond_images = cond_images, cond_scale = cond_scale, lowres_cond_img = lowres_cond_img, self_cond = self_cond, lowres_noise_times = self.lowres_noise_schedule.get_condition(lowres_noise_times)))
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 1466, in forward_with_cond_scale
>     logits = self.forward(*args, **kwargs)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 1625, in forward
>     x = init_block(x, t, c)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 708, in forward
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\einops_exts\torch.py", line 17, in forward
>     x = self.fn(x, **kwargs)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "D:\Education\University\2022\Project\Code\terrain-ml\venv\lib\site-packages\imagen_pytorch\imagen_pytorch.py", line 763, in forward
>     k = torch.cat((nk, k), dim = -2)
> RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 3 but got size 1 for tensor number 1 in the list.

[Here's](https://drive.google.com/file/d/1J14YyUspKGm_L5NHAejmnLOs4aiJwfJi/view?usp=sharing) a link to another checkpoint.

**Comment by lucidrains** [comment] 2022-09-07 23:08
hmm could you whittle this down to a script that can reproduce the error?

**Comment by daniellochner** [comment] 2022-09-08 09:29
Alright, [here's](https://github.com/lucidrains/imagen-pytorch/files/9525612/test.zip) a quick example. You can test it using [this](https://drive.google.com/file/d/1J14YyUspKGm_L5NHAejmnLOs4aiJwfJi/view?usp=sharing) checkpoint!

**Comment by lucidrains** [comment] 2022-09-08 18:48
@daniellochner ok! i'll check it out tonight if i find time

**Comment by lucidrains** [comment] 2022-09-09 15:51
@daniellochner hey Daniel, that checkpoint is way too big

do you have a minimal example I could test and reproduce the error with?

**Comment by lucidrains** [comment] 2022-09-09 15:57
@daniellochner ohh i understand what's going on, you must be using unconditional mode right? maybe my load checkpoint function doesn't work with that setting

**Comment by lucidrains** [comment] 2022-09-09 16:24
@daniellochner hey Daniel, I think I figured out the problem, but not sure how you got yourself into that state

So, after you loaded from the checkpoint, could you try placing two extra lines of code

```python
imagen = load_imagen_from_checkpoint(checkpoint).cuda()

imagen.condition_on_text = False
imagen.unconditional = True
```

**Comment by lucidrains** [comment] 2022-09-09 16:24
@daniellochner you trained your model without any text data right?

**Comment by daniellochner** [comment] 2022-09-09 16:30
> @daniellochner hey Daniel, I think I figured out the problem, but not sure how you got yourself into that state
> 
> 
> 
> So, after you loaded from the checkpoint, could you try placing two extra lines of code
> 
> 
> 
> ```python
> 
> imagen = load_imagen_from_checkpoint(checkpoint).cuda()
> 
> 
> 
> imagen.condition_on_text = False
> 
> imagen.unconditional = True
> 
> ```
> 
> 

That didn't seem to work I'm afraid!


> @daniellochner you trained your model without any text data right?

Yes!

**Comment by lucidrains** [comment] 2022-09-09 16:31
@daniellochner what is happening is the network is attempting to run cross attention to something, but from your script, there is nothing to attend to. i'm not sure why

**Comment by lucidrains** [comment] 2022-09-09 16:32
> > @daniellochner hey Daniel, I think I figured out the problem, but not sure how you got yourself into that state
> > So, after you loaded from the checkpoint, could you try placing two extra lines of code
> > ```python
> > imagen = load_imagen_from_checkpoint(checkpoint).cuda()
> > 
> > 
> > 
> > imagen.condition_on_text = False
> > 
> > imagen.unconditional = True
> > ```
> 
> That didn't seem to work I'm afraid!
> 
> > @daniellochner you trained your model without any text data right?
> 
> Yes!

oh bummer

you wouldn't be able to have a smaller model that has the same error? downloading 2GB for me will take some time

**Comment by lucidrains** [comment] 2022-09-09 16:34
unfortunately, cannot reproduce the error with the script below

let me know if your workflow was any different

```python
import torch
from imagen_pytorch.utils import load_imagen_from_checkpoint
from imagen_pytorch import ImagenConfig, ImagenTrainer

imagen = ImagenConfig(
    unets = [
        dict(dim = 16, dim_mults = (1, 2, 4, 8), layer_attns = False),
        dict(dim = 16, dim_mults = (1, 2, 4, 8), layer_attns = False)
    ],
    image_sizes = (64, 128),
    cond_drop_prob = 0.5,
    condition_on_text = False
).create()

trainer = ImagenTrainer(imagen)

trainer.save('./checkpoint.pt')

imagen = load_imagen_from_checkpoint('./checkpoint.pt')

trainer = ImagenTrainer(imagen)

inpaint_images = torch.randn(1, 3, 128, 128).cuda()      # (batch, channels, height, width)
inpaint_masks = torch.ones((1, 128, 128)).bool().cuda()  # (batch, height, width)

sampled_images = trainer.sample(inpaint_images = inpaint_images, inpaint_masks = inpaint_masks)
```

**Comment by lucidrains** [comment] 2022-09-09 16:36
@daniellochner is your error stack trace identical to the one above with the added two lines?

**Comment by daniellochner** [comment] 2022-09-09 16:36
Sure thing, here's the code: [terrain_ml.zip](https://github.com/lucidrains/imagen-pytorch/files/9537219/terrain_ml.zip)

**Comment by lucidrains** [comment] 2022-09-09 16:38
@daniellochner you need to pass in the terrain descriptions in as an array of text, so

```python
terrain_text = ['rocky', 'smooth', 'has water']  // where length is equal to the number of inpainting images
```

**Comment by lucidrains** [comment] 2022-09-09 16:40
@daniellochner to train without text, you need to pass in 

```python
ImagenConfig(condition_on_text = False)
```

**Comment by daniellochner** [comment] 2022-09-09 16:41
When training, I specify `args.descriptions` in the imagen, and that sets it to be conditioned on text.

I don't necessarily specify sample descriptions, so it's None for the unconditional model. Still use the same code though!

**Comment by lucidrains** [comment] 2022-09-09 16:43
@daniellochner hmmm, that should not be allowed if `condition_on_text` is not set to `False`

let me go fix that haha

**Comment by lucidrains** [comment] 2022-09-09 16:43
@daniellochner yea, your error trace means there are cross attention blocks (the neural network is attending to the text)

**Comment by daniellochner** [comment] 2022-09-09 16:45
Hmm, when specifying texts, I still get the same error:
`samples = imagen.sample(texts=["","",""], inpaint_images=inpaint_images_tmp, inpaint_masks=inpaint_masks, return_pil_images=True)`

**Comment by lucidrains** [comment] 2022-09-09 16:50
@daniellochner try adding something within the quotes

added some more checks too, so it should error with something more informative if you do not add text https://github.com/lucidrains/imagen-pytorch/commit/77cc6a3192f4675ee524d2939fa552e5276da9f7

**Comment by daniellochner** [comment] 2022-09-09 16:52
> @daniellochner try adding something within the quotes
> 
> added some more checks too, so it should error with something more informative if you do not add text [77cc6a3](https://github.com/lucidrains/imagen-pytorch/commit/77cc6a3192f4675ee524d2939fa552e5276da9f7)

Yup, I've tried adding text within the quotes as well!

**Comment by lucidrains** [comment] 2022-09-09 16:57
@daniellochner is it still the same error as above or different?

**Comment by daniellochner** [comment] 2022-09-09 16:58
The same error.

**Comment by lucidrains** [comment] 2022-09-09 17:07
don't worry, we'll save your school project, gimme 5

**Comment by daniellochner** [comment] 2022-09-09 17:09
Yup, slurm output shows my Makefile command:
```
make: Entering directory `/home/lchdan004/terrain-ml'
source venv/bin/activate
python3 src/terrain_ml.py \
	-terrains /scratch/lchdan004/terrain-ml/input/data/u/terrains \
	-samples output/samples \
	-logs output/logs \
	-checkpoints /scratch/lchdan004/terrain-ml/checkpoints \
	-checkpoint undefined
training with dataset of 137560 samples and validating with randomly splitted 3528 samples
...
```

What is interesting though is that it used Python 3.6.8...?

**Comment by daniellochner** [comment] 2022-09-09 17:09
> don't worry, we'll save your school project, gimme 5

Haha, my hero! 🤣

**Comment by daniellochner** [comment] 2022-09-09 17:22
Oh right, one thing with the code I shared is that I exposed `train_size` and `valid_size` in `trainer.py`, since I wanted to calculate average loss as I trained!

**Comment by lucidrains** [comment] 2022-09-09 17:28
@daniellochner ok, try this new version i just committed in

and also add this line after you loaded your imagen

```python
imagen.force_unconditional_()
```

**Comment by daniellochner** [comment] 2022-09-09 17:31
BOOM! It works! You're a legend! 😄

Thank you so much!

**Comment by lucidrains** [comment] 2022-09-09 17:46
@daniellochner just make sure you truly did not condition on anything during training and the 2GB network should be still usable

**Comment by lucidrains** [comment] 2022-09-09 17:47
@daniellochner go make your professor's and teacher's heads spin :)

**Closed** 2022-09-09 17:49 UTC

**Comment by universewill** [comment] 2022-11-23 13:44
> @daniellochner ok, try this new version i just committed in
> 
> and also add this line after you loaded your imagen
> 
> ```python
> imagen.force_unconditional_()
> ```
Good work
